// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_12_FONT_ID (1699943478)
#define BOOKERLY_14_FONT_ID (1116187566)
#define BOOKERLY_16_FONT_ID (-1221793056)
#define NOTOSANS_12_FONT_ID (-1454145634)
#define NOTOSANS_14_FONT_ID (-1633990712)
#define NOTOSANS_16_FONT_ID (296210921)
#define UI_10_FONT_ID (-1049782577)
#define UI_12_FONT_ID (1941774187)
#define SMALL_FONT_ID (-1693641982)
